In [1]:
import numpy as np
N = np.array([420000, 440000, 460000, 480000, 500000]) 

In [2]:
10*np.log(2*N)-(1/8)*0.0025*N - np.log(0.95/4)

array([  6.59915936,   0.81435952,  -4.99112285, -10.81552671, -16.65730676])

In [46]:
N = 10000
dvc = 50
theta = 0.05
a = np.sqrt( (8/N) * (np.log(4) + 50*np.log(2*N) - np.log(0.05)) )
b = np.sqrt( (2/N) * (np.log(2) + 51*np.log(N)) ) + np.sqrt( (2/N)*-np.log(theta) ) + 1/N
c = np.sqrt( (1/N) * (0.1 + (np.log(6) + 50*np.log(2*N) - np.log(theta) ) ) )
d = np.sqrt( (1/(2*N)) * ((0.2*1.05) + (np.log(4) + 100*np.log(N) - np.log(theta) ) ) )
e = np.sqrt( (16/N) * (np.log(2) + 50*np.log(N) - (1/2)*np.log(0.05)) )
a, b, c, d, e

(0.63217491520083602,
 0.33130878596163948,
 0.22362063173365476,
 0.21513089780785702,
 0.86042597070627391)

In [33]:
#HW3-7
u,v = 0,0
for i in range(6):
    print(i)
    print(u,v)
    new_u = np.exp(u) + v*np.exp(u*v) + 2*u - 2*v - 3
    new_v = 2*np.exp(2*v) + u*np.exp(u*v) - 2*u + 4*v - 2
    new_u = np.round(new_u, decimals=4) 
    new_v = np.round(new_v, decimals=4)
    u = u - 0.01*new_u
    v = v - 0.01*new_v

0
0 0
1
0.02 0.0
2
0.039398 0.0002
3
0.05821 0.000578
4
0.076452 0.001114
5
0.09414 0.001789


In [34]:
u,v = 0.09414,0.001789
e = np.exp(u) + np.exp(2*v) + np.exp(u*v) + np.power(u, 2) - 2*u*v + 2*np.power(v, 2) - 3*u -2*v
e

2.8250003020959809

In [35]:
u,v = 0,0
E = np.exp(u) + np.exp(2*v) + np.exp(u*v) + np.power(u,2) - 2*u*v + 2*np.power(v,2) - 3*u -2*v
E_u = np.exp(u) + v*np.exp(u*v) + 2*u - 2*v - 3
E_uu = np.exp(u) + np.power(v,2)*np.exp(u*v) + 2
E_v = 2*np.exp(2*v) + u*np.exp(u*v) - 2*u + 4*v - 2
E_vv = 4*np.exp(2*v) + np.power(u,2)*np.exp(u*v) + 4
E_uv = u*v*np.exp(u*v) + np.exp(u*v) - 2
[E_uu/2, E_vv/2, E_uv, E_u, E_v, E]

[1.5, 4.0, -1.0, -2.0, 0.0, 3.0]

In [38]:
H = np.matrix([[E_uu, E_uv], [E_uv, E_vv]])
H

matrix([[ 3., -1.],
        [-1.,  8.]])

In [4]:
import numpy as np
from numpy.linalg import inv
uv = np.matrix([0,0])
for i in range(6):
    print(i)
    u,v = uv[0,0],uv[0,1] 
    E_u = np.exp(u) + v*np.exp(u*v) + 2*u - 2*v - 3
    E_v = 2*np.exp(2*v) + u*np.exp(u*v) - 2*u + 4*v - 2
    E_uu = np.exp(u) + np.power(v,2)*np.exp(u*v) + 2
    E_vv = 4*np.exp(2*v) + np.power(u,2)*np.exp(u*v) + 4
    E_uv = u*v*np.exp(u*v) + np.exp(u*v) - 2
    H = np.matrix([[E_uu, E_uv], [E_uv, E_vv]])
    H_inv = inv(H)
    uv = uv - np.dot(np.matrix([E_u, E_v]), H_inv)
    print(uv)
u,v = uv[0,0],uv[0,1] 
E = np.exp(u) + np.exp(2*v) + np.exp(u*v) + np.power(u, 2) - 2*u*v + 2*np.power(v, 2) - 3*u -2*v
print(E)

0
[[ 0.69565217  0.08695652]]
1
[[ 0.61376222  0.0711079 ]]
2
[[ 0.61181286  0.07050006]]
3
[[ 0.61181172  0.07049955]]
4
[[ 0.61181172  0.07049955]]
5
[[ 0.61181172  0.07049955]]
2.36082334564


In [4]:
#HW4-9
N = 10000
x = 2/np.exp(2)
x

0.2706705664732254